# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.1.3'

gem 'bcrypt', '~> 3.1', '>= 3.1.12'
gem 'erubis'
gem 'puma'
gem 'redcarpet', '~> 3.5', '>= 3.5.1'
gem 'sinatra', '~> 3.0', '>= 3.0.3'
gem 'sinatra-contrib'

group :development do
  gem 'rake', '~> 13.0'
end

group :test do
  gem 'minitest', '~> 5.16'
  gem 'minitest-reporters', '~> 1.5'
  gem 'rack-test'
  gem 'simplecov'
end
