# frozen_string_literal: true

require 'rake/testtask'

desc 'Run tests'
task default: :test

desc 'Run test suite'
Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.pattern = 'test/**/*_test.rb'
end

Rake::Task[:test].enhance do
  require './test/auth/helpers'
  Test::Auth::Helpers::TempUsers.destroy
end
